# Generated by Django 4.1.4 on 2022-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='شماره مبایل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='تصویر کاربر')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_employer', models.BooleanField(default=False)),
                ('is_job_seeker', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
    ]
