# Generated by Django 4.1.4 on 2023-01-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_employer_user_is_job_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_job_seeker',
        ),
    ]
