# Generated by Django 4.1.4 on 2022-12-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس اینترنتی')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('skill', models.CharField(max_length=150, verbose_name='حرفه')),
                ('status', models.CharField(choices=[('t', 'متاهل'), ('j', 'مجرد')], default='Z', max_length=1, verbose_name=' تاهل')),
                ('education', models.CharField(max_length=100, verbose_name='مقطع تحصیلی')),
                ('university', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('field', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('english', models.CharField(max_length=100, verbose_name='میزان تسلط شما به زبان انگلیسی')),
                ('language', models.CharField(max_length=100, verbose_name='آیا به زبان دیگری تسلط دارید؟')),
                ('project', models.CharField(max_length=100, verbose_name='پروژه های کاری')),
                ('certificate', models.CharField(max_length=100, verbose_name='گواهی نامه ها و افتخارات')),
                ('dore', models.CharField(max_length=100, verbose_name='دوره ها')),
                ('job', models.CharField(max_length=100, verbose_name='تجربه شغلی')),
                ('last_job_situation', models.CharField(max_length=100, verbose_name='آخرین موقعیت شغلی')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه ها',
            },
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='موضوع')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس پست')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('company', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('description', models.TextField(max_length=9000, verbose_name='متن آگهی')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='آپلود عکس')),
                ('Create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار آگهی')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی پست')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='p', max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='advertise', to='advertising.category', verbose_name='موقعیت شغلی')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
