# Generated by Django 4.1.4 on 2022-12-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_rename_user_resume_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='User',
            new_name='user',
        ),
    ]
