# Generated by Django 4.1.4 on 2022-12-27 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0004_remove_advertise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='title',
            field=models.CharField(default=None, max_length=150, verbose_name='موضوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertise',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده'),
            preserve_default=False,
        ),
    ]
