# Generated by Django 4.1.4 on 2022-12-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_advertise_title_advertise_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'ordering': ('-create',), 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='Create',
            new_name='create',
        ),
    ]
