# Generated by Django 4.1.4 on 2022-12-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_alter_advertise_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='dore',
            new_name='courses',
        ),
    ]
