# Generated by Django 4.1.4 on 2022-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_rename_dore_resume_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images', verbose_name='آپلود عکس'),
        ),
    ]
