# Generated by Django 4.1.4 on 2022-12-31 13:12

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_alter_advertise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from=['title'], unique=True, verbose_name='آدرس'),
        ),
    ]
