# Generated by Django 4.1.4 on 2022-12-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0011_alter_advertise_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
