# Generated by Django 4.1.4 on 2022-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=1000)),
                ('employer_call', models.CharField(max_length=15)),
                ('job_searcher_call', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('telegram', models.URLField(max_length=600)),
            ],
        ),
    ]
