# Generated by Django 4.1.4 on 2022-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
